name: Build Executable File

on:
  push:
    branches:
      - master
    tags:
      - v*

permissions: write-all

jobs:
  build_package:
    name: Build Executable File
    runs-on: windows-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.2.0

      # - name: Setup SSH Key
      #   uses: shimataro/ssh-key-action@v2.7.0
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: unnecessary
      #     config: |
      #       Host *
      #         StrictHostKeyChecking no
      #         UserKnownHostsFile=/dev/null
      #     if_key_exists: replace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./target/release/${{ github.event.repository.name }}.exe
          name: ${{ github.event.repository.name }}.exe
          if-no-files-found: ignore
          retention-days: 7
          compression-level: 6
          overwrite: true

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.exe
          path: ${{ github.event.repository.name }}.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.event.repository.name }}.exe
